USE triviaad2016;
insert into equipos (Nombre,ScoreFinal,NoParticipantes) values
('CHICOS QUE LLORAN',0,5),
('CAZADORES DE LIBROS',0,5),
('ATMAN',0,5),
('EL INTENTO SE HIZO "THE RETURN"',0,5),
('BIRDS',0,5),
('2^2+1',0,5),
('THE CORE',0,5),
('CDS-SILVER',0,5),
('REMEDIAL SQUAD',0,5);

Insert into libros (nombre,Genero,Autor) values
('La chica del Tren','Novela','Paula'),
('Yo antes de ti','Romance','Jojo Moyes'),
('Dr. Sueño','Terror','Stephen King'),
('1984','Clásico','George Orwell'),
('Fausto','Novela filosófica',' Johann Wolfgang von Goethe'),
('Ángeles y Demonios','Ficción','Dan Brown'),
('Memorias de una Geisha','Novela histórica','Arthur Golden'),
('120 días de Sodoma','Erótica','Marqués de Sade');

Insert into participantes (id_participante,id_equipo,Nombre) values
(1,1,'José Andrés González Toledo'),
(2,1,'José Guadalupe Magaña Díaz'),
(3,1,'Julio Cesar Gómez Ortiz'),
(4,1,'Rolando Flores Léon'),
(5,1,'Juan Fernado de Jesús Fernández Villagómez'),
(1,2,'Alberto Ángel Aguado Reyes'),
(2,2,'José Armando López Acosta'),
(3,2,'Cruz Martín Tapia Medina'),
(4,2,'Efraín Jared Ramirez Díaz'),
(5,2,'Paloma Elizabeth González Durán'),
(1,3,'Jorge Guzmán Ramos'),
(2,3,'Efrén Vega Chavez'),
(3,3,'Juan Carlos Guzmán Contreras'),
(4,3,'Leonel Estrada Rojo'),
(5,3,'Edgar Andrade Corona'),
(1,4,'Delia Azarel López González'),
(2,4,'María Elizabeth Vazquez Gómez'),
(3,4,'Gabriel Rodríguez Vieyra'),
(4,4,'Jhonatan Sanchez Juarez'),
(5,4,'Alejandro Anguiano'),
(1,5,'Melisa Torres Rangel'),
(2,5,'Brenda Estefanía Lopez Avalos'),
(3,5,'Hilary Balcazar Ortiz'),
(4,5,'Jesús Abraham Valdez Lara'),
(5,5,'Teresa Herrejón Perez'),
(1,6,'Lucia ayala Franco'),
(2,6,'María Tirnidad Pimentel Villegas'),
(3,6,'Salvador Santoyo Celerón'),
(4,6,'Erika Martínez Martínez'),
(5,6,'Giezi Anahi Jaimes Valle'),
(1,7,'Eduardo Gómez Cortes'),
(2,7,'Luis Fernando Zavala Bibián'),
(3,7,'Andrea Esquivel Galan'),
(4,7,'Michelle Arileni Balcazar Ortíz'),
(5,7,'Caren Vigil Patiño'),
(1,8,'Patricia Vega Flores'),
(2,8,'Gustavo Iván Vega Olvera'),
(3,8,'Luis Germán Gutierres Torres'),
(4,8,'David Morales Orozco'),
(5,8,'Patricia Alcantar Ortiz'),
(1,9,'Jose Miguel Lara Yepes'),
(2,9,'Miguel Angel Ortiz Villicaña'),
(3,9,'Viridiana Lopez Lopez'),
(4,9,'Karla Yazmin Garcia Perez'),
(5,9,'Francisco Javier Tinoco Hurtado');